### ISSUE TITLE
mb-smf crash when creating a Broadcast MBS Session indicating nonexistent TMGI

### ISSUE THREAD

**Issue by igonzalez-nem** [iTEAM-MCG/5G-MBS-playground#5]
When executing a request for creating a new MBS Session indicating a tmgi that has not previously been allocated (indicating an mbsServiceId that does not belong to any allocated tmgi) with curl, `curl: (56) Recv failure: Connection reset by peer` is received as error response if log level debug is configured, while `curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream` is received as error response if log level is left as default.

After this, all following requests fail with reason `curl: (6) Could not resolve host: mb-smf.open5gs.org`
When checking the logs of the SMF MBS docker, the following can be seen:

```
mb-smf  | 07/11 11:42:40.365: [smf] DEBUG: MBS Session create request received (../src/smf/nmbsmf-handler.c:298)
mb-smf  | 07/11 11:42:40.365: [sbi] DEBUG: STATUS [404] (../lib/sbi/nghttp2-server.c:640)
mb-smf  | 07/11 11:42:40.365: [sbi] DEBUG: SENDING...: 136 (../lib/sbi/nghttp2-server.c:648)
mb-smf  | 07/11 11:42:40.365: [sbi] DEBUG: {"title":"Unknown TMGI","detail":"Requested MBS Session Create failed, TMGI provided expired or cannot be found","cause":"UNKNOWN_TMGI"} (../lib/sbi/nghttp2-server.c:649)
mb-smf  | 07/11 11:42:40.365: [sbi] DEBUG: STREAM closed [1] (../lib/sbi/nghttp2-server.c:1268)
mb-smf exited with code 139
```

In case of  trying to trying to refresh a TMGI not previously allocated, the error is properly handled, response `{"title":"Unknown TMGI","detail":"Requested TMGI Allocate (refresh) failed, TMGI expired or cannot be found","cause":"UNKNOWN_TMGI"}` is received and the SMF MBS continues to work without crashing. Hence the issue seems specific for the stream handling for the nmbsmf-mbssession/v1/mbs-sessions endpoint.

Reproducing the issue is easy, just launch the MBS Playground (`docker compose up -d`) connect to the AF container (`docker exec -it af bash`) and launch a request for creating a new MBS Session:
```
curl --http2-prior-knowledge \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{ "mbsSession": { "mbsSessionId": { "tmgi": { "mbsServiceId": "9236F7", "plmnId": { "mcc":"001", "mnc":"01" } } }, "ssm": { "sourceIpAddr": { "ipv4Addr": "10.33.33.3" }, "destIpAddr": { "ipv4Addr": "239.0.0.20" } }, "serviceType":"BROADCAST" } }' \
  mb-smf.open5gs.org:80/nmbsmf-mbssession/v1/mbs-sessions
```

**Comment by Borjis131** [comment]
Hi @igonzalez-nem,
The issue has been fixed with [this commit](https://github.com/5G-MAG/open5gs/commit/db4b50214948857cece67031ddbb09137c8fb552), although the fix to the containers will be available in the near future. 

Thanks a lot for the issue! Remember to follow the new updates [here](https://github.com/5G-MAG/rt-mbs-examples)
